### ISSUE TITLE
`terraform validate` errors when `refresh_token` is provided via an environment variable

### ISSUE THREAD

**Issue by oliver-hohn** [SquadcastHub/terraform-provider-squadcast#12]
## Summary
We're using the Squadcast TF provider to configure our services and alerts. To configure the provider, we're passing in the `region` as an argument into the provider and using the `SQUADCAST_REFRESH_TOKEN` environment variable to pass in the `refresh_token`:
```tf
provider "squadcast" {
  # SQUADCAST_REFRESH_TOKEN env var is set.
  region = var.squadcast_region
}
```

This works fine when running `terraform plan` and `terraform apply`, however, we're getting errors when running `terraform validate` to check the syntax and logic (https://www.terraform.io/cli/commands/validate).

## Expected Behaviour
```sh
$ terraform validate

Success! The configuration is valid.
```

## Actual Behaviour
```sh
$ terraform validate

│ Error: Missing required argument
│
│   on main.tf line 116, in provider "squadcast":
│  116: provider "squadcast" {
│
│ The argument "refresh_token" is required, but no definition was found.
```

## Possible Solution
Looking at the code, and comparing the `provider` set up to other TF providers (e.g. [how the AWS provider considers the `secret_key` to be optional](https://github.com/hashicorp/terraform-provider-aws/blob/a97d9d568f8ea98d7e63aa7d6aa128f0175a0758/internal/provider/provider.go#L333-L338)), I think we can set the `refresh_token` to be `Optional` rather than `Required`, and enforce latter down the line that the `refresh_token` is not empty: https://github.com/SquadcastHub/terraform-provider-squadcast/blob/e1119642089388df67366048174c72cccd4bdc1e/internal/provider/provider.go#L68-L74

I'm happy to raise a PR with these changes if you're happy with this approach.

**Comment by roshan8** [comment]
@oliver-hohn Thanks for reporting the issue. let me take a look.

**Comment by roshan8** [comment]
@oliver-hohn Your approach looks good!
We are open to accepting contributions from the community. Really appreciate if you can raise a PR :)

**Comment by oliver-hohn** [comment]
Thanks @roshan8 :+1: I'll try and raise a PR over the next couple of days

**Comment by Lucifer8729** [comment]
I'll be picking this up
