### ISSUE TITLE
Allow 0 tags in squadcast_tagging_rules

### ISSUE THREAD

**Issue by rmocnik** [SquadcastHub/terraform-provider-squadcast#17]
Schema for `rules` in [squadcast_tagging_rules](https://registry.terraform.io/providers/SquadcastHub/squadcast/latest/docs/resources/tagging_rules#nested-schema-for-rules) requires at least 1 tag, while Squadcast web interface allows specifying Tag Expression without any Tag Mapping. Schema should be updated to allow zero tags.

**Comment by roshan8** [comment]
@rmocnik Thanks for reporting the issue, I'll take a look.

**Comment by roshan8** [comment]
@rmocnik We have released a new version v1.0.7 where tags are optional.
However, don't forget to pass tags via expression when tags parameters are not set.
An example of this is given in the [docs](https://registry.terraform.io/providers/SquadcastHub/squadcast/latest/docs/resources/tagging_rules)
