### ISSUE TITLE
squadcast_team_role data source is missing

### ISSUE THREAD

**Issue by pawelros** [SquadcastHub/terraform-provider-squadcast#23]
In [squadcast_team_member  resource documentation](https://registry.terraform.io/providers/SquadcastHub/squadcast/1.0.4/docs/resources/team_member), example usage `squadcast_team_role` is used. The problem is that when I want to do the same:

```
data "squadcast_team_role" "team_role" {
  name = "user"
 }
```

I get the following error:

```
│ The provider squadcasthub/squadcast does not support data source
│ "squadcast_team_role".
│ 
│ Did you intend to use the managed resource type "squadcast_team_role"? If
│ so, declare this using a "resource" block instead of a "data" block.
```

This data source type is also missing in documentation `Data sources` section.
So how can I add a new team member if I cannot query for team role ids?

**Comment by roshan8** [comment]
Thanks for reporting the issue @pawelros 
At the moment we are not supporting data source for the team roles. We are currently working on that.
We will update here once it gets released.
