### ISSUE TITLE
release 1.0.9 isn't patch version

### ISSUE THREAD

**Issue by r-mironov** [SquadcastHub/terraform-provider-squadcast#27]
Hello guys!

You've recently released the new `patch` version `1.0.9`, which looks fantastic. But it doesn't satisfy the patch requirements:
1) There are breaking changes: at least `move alert source api to alert_source` (https://github.com/SquadcastHub/terraform-provider-squadcast/pull/26/commits/1463c4b3efd0699d4df0fe0136a36a608fc3ba2e)
2) There are new features

It should be a `major` version according to the semver https://semver.org/

**Comment by mohammadmuazam** [comment]
Hey, this is not a breaking change, it's not something that was already there and moved/removed.
Adding Alert Sources is a new feature in service catalog, and this version bought the support for it into terraform.
Yes, I do agree with incrementing major version for feature edition!

**Comment by r-mironov** [comment]
Yeah, my bad, wrong commit

So after upgrading from `1.0.8` to `1.0.9` we faced with `squadcast_service.service_name` doesn't have `alert_source_endpoints`

We have the output:
```
output "service" {
  value       = squadcast_service.service_name
  description = "Created service"
}
```
And plan shows something like this:
```
Changes to Outputs:
      ~ service  = {
          - alert_source_endpoints = {
              - "admin-labs"  = "https://api.squadcast.com/v1/incidents/admin-labs/token"
              - ...
              } -> null
```

Can https://github.com/SquadcastHub/terraform-provider-squadcast/commit/61e24c3ddd3a140eb7baec0cb7b5fb87311b0dd5#diff-faeca4b7b0e45e83cf08e7e8205591b7eb2f18d3986e3b81836c9603d335ef9fL81 these changes be the cause of such behavior?

**Comment by mohammadmuazam** [comment]
Can you use the latest version 1.1.0, we have removed the version 1.0.9 due to this bug.
