### ISSUE TITLE
using version 1.0.9 it gives error (failed to install provider)

### ISSUE THREAD

**Issue by dhaval512** [SquadcastHub/terraform-provider-squadcast#30]
Initializing provider plugins...
- Finding squadcasthub/squadcast versions matching "1.0.9"...
╷
│ Error: Failed to install provider
│ 
│ Error while installing squadcasthub/squadcast v1.0.9: could not query provider registry for registry.terraform.io/squadcasthub/squadcast:
│ failed to retrieve authentication checksums for provider: 404 Not Found returned from github.com

**Comment by NandanSquadcast** [comment]
Can you use the latest version 1.1.0, we have removed the version 1.0.9 due to a certain bug
