### ISSUE TITLE
Time-based Suppression Rules

### ISSUE THREAD

**Issue by Supercheez** [SquadcastHub/terraform-provider-squadcast#34]
Hi team,

Is there a way to set up time-based suppression rules by using a non-basic rule, or do I need to wait for this functionality to reach the terraform provider?

I would love to be able to suppress all out-of-hours notifications for our non-production environments!

Thanks

**Comment by roshan8** [comment]
Hello @Supercheez, Thanks for reporting this 
Our team is working on this, It should be released in one week's time.

**Comment by roshan8** [comment]
@Supercheez This feature has been released with v1.3.0. 
Do let us know if you face any problems!

**Comment by Supercheez** [comment]
Thanks @roshan8, that all seems to be working perfectly!
