### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by charlyhue** [SquadcastHub/terraform-provider-squadcast#4]
Hello,

The Squadcast provider does not support ARM processors.

Can you post a compatible version on the terraform registry please?

Thank you

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/30727779/151197376-7a7551e8-1f5e-4bce-9786-b4fc671c3260.png">

**Comment by roshan8** [comment]
Thanks for reporting the issue. I have created a PR for the same :)

**Comment by charlyhue** [comment]
It's work in [v0.5.15](https://github.com/SquadcastHub/terraform-provider-squadcast/releases/tag/v0.5.15) Thank you :)
