### ISSUE TITLE
Support lifecycle blocks for all resources

### ISSUE THREAD

**Issue by ghost** [SquadcastHub/terraform-provider-squadcast#42]
For example, with the not-yet-supported new scheduling, being able to use lifecycle blocks would have been very useful. As it stands now we have to remove and hard code resources as a work-around.

When trying to use the block:

```
Error: Unsupported block type

  on squadcast.tf line 256, in resource "squadcast_escalation_policy" "escalation_policy":
 256:     lifecycle {

Blocks of type "lifecycle" are not expected here.
```

**Comment by roshan8** [comment]
Thanks for reporting this @houserx-jmcc 

Are you requesting data source support on the new schedule or lifecycle option on the escalation policy?

**Comment by ghost** [comment]
Both would be nice, but this specific request is just for lifecycle options. Needing it for the new schedules was just an example of the value :)

**Comment by dheeraj-squadcast** [comment]
@houserx-jmcc AFAIK `lifecycle` is provided by terraform directly, I'm not sure if we need to do anything to enable it, but we'll do some research. 

Also, what you received *can* be an error in response to an invalid resource ([1](https://github.com/hashicorp/terraform/issues/24188), [2](https://github.com/hashicorp/terraform/issues/21995)). Could you confirm that it's not one of those cases?

**Comment by ghost** [comment]
Yes, it was added to an existing resource that functions properly otherwise.
