### ISSUE TITLE
Support to schedulev2

### ISSUE THREAD

**Issue by caiohasouza** [SquadcastHub/terraform-provider-squadcast#45]
Hi,

I have some problems after ScheduleV2 migration, at my terraform state i have some diferences and i'm trying fixing, but the provider don't support "schedulev2" item type, currently it's the value configured:

```
~ targets {
  ~ id   = "000000000000000000000000" -> "623a6435df616c292febe743"
  ~ type = "schedulev2" -> "schedule"
}
```

If i change the value of type to schedulev2 i have this error:
```
Error: expected rules.0.targets.0.type to be one of [user squad schedule], got schedulev2
  on escalation-policy.tf line 24, in resource "squadcast_escalation_policy" "xxxx":
  24:       type = "schedulev2"
```

Could you help us?

Regards

**Comment by roshan8** [comment]
The provider version v1.4.0 has been released, enabling Terraform support for the new schedule! 
This update allows for both schedule and rotation management. To provision new schedules, please utilize the `schedule_resource_v2` and avoid importing legacy schedules into new resources, as the two utilize distinct APIs. 

A few examples are also added for the creation of weekly & custom rotations :)

**Comment by caiohasouza** [comment]
Hi,

Cool, i proceeded with adjusts but i found another issue with "squadcast_escalation_policy", when i change the target type to schedulev2 i have this error:

```
Error: expected length of rules.0.targets.0.id to be in the range (24 - 24), got 15059

  on escalation-policy.tf line 9, in resource "squadcast_escalation_policy" "support":
   9:       id   = squadcast_schedule_v2.support_business_hours.id



Error: expected rules.0.targets.0.type to be one of [user squad schedule], got schedulev2

  on escalation-policy.tf line 10, in resource "squadcast_escalation_policy" "support":
  10:       type = "schedulev2"
```

Could you help me?

Regards

**Comment by chriselion** [comment]
Same problem here when I tried to use a `squadcast_schedule_v2` Data Source - the ID is too short ("552") to be passed to an squadcast_escalation_policy.

**Comment by roshan8** [comment]
This bug has been addressed in the v1.4.3 provider release.

**Comment by caiohasouza** [comment]
Perfect, all works fine now, thank you!

**Comment by chriselion** [comment]
Yup, looking good for me too.
