### ISSUE TITLE
Add ability to set Service's slack channel

### ISSUE THREAD

**Issue by chriselion** [SquadcastHub/terraform-provider-squadcast#50]
I'd like to be able to set the slack channel for a `squadcast_service` resource. It looks this is supported in the API already: https://apidocs.squadcast.com/#04a46bd8-1b08-4d9e-8efb-ee9339450d58 - any idea if it'll be coming to the terraform provider soon?

(I had previously mentioned this in support chat, but wanted to post here for better visibility)

**Comment by roshan8** [comment]
This feature was added with the provider release version`v1.4.4`.

**Comment by chriselion** [comment]
Thanks, this looks promising. One bit of initial feedback is that it would be much more convenient to set the channel by name (`#alerts-foo-service`) instead of the ID. I was optimistic and tried passing the name, and that gave a 500 response from the API
```
│ Error: PUT https://api.squadcast.com/v3/services/<redacted>/extensions returned an error:
│ [500] Status code error: 500%!(EXTRA string=An API error occurred: channel_not_found)
│ 
│   with module.squadcast_services[<redacted>].squadcast_service.service,
│   on ../modules/squadcast-services/main.tf line 15, in resource "squadcast_service" "service":
│   15: resource "squadcast_service" "service" {
```

I realize this is probably a limitation of the API, not the terraform provider specifically.

**Comment by chriselion** [comment]
For anybody else looking to use the slack channel name to look up the ID, this seems to work well
https://registry.terraform.io/providers/pablovarela/slack/latest/docs/data-sources/conversation
