### ISSUE TITLE
Changes to list order causes diffs in Terraform plans

### ISSUE THREAD

**Issue by akennealy** [SquadcastHub/terraform-provider-squadcast#54]
## Overview
Every time I run a plan, I get the same diffs that that only detect/apply a change to the list order.
I see this with the following resources, though I'm sure there's others:

1) squadcast_service ([dependencies](https://registry.terraform.io/providers/SquadcastHub/squadcast/latest/docs/resources/service#dependencies) list)
2) squadcast_team_role ([abilities](https://registry.terraform.io/providers/SquadcastHub/squadcast/latest/docs/resources/team_role#abilities) list)
3) squadcast_user ([abilities](https://registry.terraform.io/providers/SquadcastHub/squadcast/latest/docs/resources/user#abilities) list)

Example:
![image](https://github.com/SquadcastHub/terraform-provider-squadcast/assets/8302190/5f788b8d-9df7-44c2-9542-7c126c8d6f5c)
Or: 
![image](https://github.com/SquadcastHub/terraform-provider-squadcast/assets/8302190/3cd6111b-42d3-415f-9e86-297ad2d8696d)

**Comment by roshan8** [comment]
@akennealy This issue has been addressed in provider version `v1.4.5`. Do let us know if you face any issues

**Comment by akennealy** [comment]
> @akennealy This issue has been addressed in provider version `v1.4.5`. Do let us know if you face any issues

@roshan8 Thank you! We'll try it out.
