### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by applike-ss** [SquadcastHub/terraform-provider-squadcast#6]
Hi,

is there any plans to add more resources? Just having the services isn't very helpful imho.
We would like to see the ability to manage squads, users, teams, service tagging rules, services routing rules etc. etc. etc.

best,
applike-ss

**Comment by roshan8** [comment]
hi @applike-ss 
The recent version of the provider supports most of the resources.
Please check out [v1.0.3](https://registry.terraform.io/providers/SquadcastHub/squadcast/latest)
