### ISSUE TITLE
Cannot create Service for non-default team

### ISSUE THREAD

**Issue by Supy** [SquadcastHub/terraform-provider-squadcast#7]
It is currently not possible to create a Service for a non-default team using the Terraform provider as it does not accept `owner_id` as an input argument. [According to the API documentation](https://apidocs.squadcast.com/#f46b767a-b0d3-4e01-8061-28390b56290f), Squadcast already supports passing in `owner_id` when creating a Service. It would be helpful to allow a Service to also accept this `owner_id` argument.

**Comment by roshan8** [comment]
Thanks for raising the issue :) 
This has been addressed with the recent release
Please check the [latest](https://registry.terraform.io/providers/SquadcastHub/squadcast/latest) version of the provider.
