### ISSUE TITLE
squadcast_schedule resource results in 410 response code from server

### ISSUE THREAD

**Issue by deon-vector** [SquadcastHub/terraform-provider-squadcast#72]
When trying to create a schedule using "squadcast_schedule" you get an error:

```
│ Warning: Deprecated Resource
│ 
│   with squadcast_schedule.backend_eng,
│   on main.tf line 48, in resource "squadcast_schedule" "backend_eng":
│   48: resource "squadcast_schedule" "backend_eng" {
│ 
│ This resource is deprecated, please use `squadcast_schedule_v2` instead.
╵
╷
│ Error: POST https://api.squadcast.com/v3/schedules returned 410 with an unexpected error: struct { Data *api.Schedule "json:\"data\""; *api.Meta }{Data:(*api.Schedule)(nil), Meta:(*api.Meta)(nil)}
│ 
│   with squadcast_schedule.backend_eng,
│   on main.tf line 48, in resource "squadcast_schedule" "backend_eng":
│   48: resource "squadcast_schedule" "backend_eng" {
│ 
``` 

You should remove any mention of "squadcast_schedule" resource or maybe put a big bold "DEPRECATED" notice at the top in your documentation

**Comment by roshan8** [comment]
@deon-vector `squadcast_schedule` is a legacy resource. and it is going to be deprecated soon. 
Currently, these APIs are enabled only for a few of our customers.

Thanks for the suggestion on the deprecation message. We have updated the warning message in the latest release.
