### ISSUE TITLE
broken link on squadcast_schedule_v2 resource documentation

### ISSUE THREAD

**Issue by deon-vector** [SquadcastHub/terraform-provider-squadcast#73]
https://registry.terraform.io/providers/SquadcastHub/squadcast/latest/docs/resources/schedule_v2

The documentation has a link "[Squadcast schedules v2](https://support.squadcast.com/docs/schedules-new)"  that brings you to https://support.squadcast.com/docs/schedules-new  but that URL is not valid, Page Not Found.

It'd be nice if you also made it very apparent the difference between "squadcast_schedule" vs "squadcast_schedule_v2"

**Comment by roshan8** [comment]
@deon-vector Thanks for reporting this!
We have fixed this with the recent release (version: v1.6.5)
