### ISSUE TITLE
What are the available notification channels?

### ISSUE THREAD

**Issue by deon-vector** [SquadcastHub/terraform-provider-squadcast#75]
https://registry.terraform.io/providers/SquadcastHub/squadcast/latest/docs/resources/escalation_policy#notification_channels

The documentation does not specify the valid notification channels. Only mentions it's a list.  The example does show that "Email" is one of the items but what are the others? push or Push?  email or EMail or Email or E-Mail? SMS or text or Text?

**Comment by roshan8** [comment]
Thanks for reporting this. We have updated the doc with a new release (v1.6.6)
