### ISSUE TITLE
Service Maintainer is now required

### ISSUE THREAD

**Issue by Supercheez** [SquadcastHub/terraform-provider-squadcast#82]
Hi there,

In version 1.6.9 the maintainer property of a squadcast_service was made a required field. This is a breaking change, so to see it included in a patch release is disappointing - can you advise whether this was intended?

Many thanks

**Comment by roshan8** [comment]
Thank you for bringing this to our attention. It appears this issue was overlooked. Rest assured, we'll ensure it's addressed in the future releases.
