### ISSUE TITLE
Error using dataprovider `squadcast_squad` on version 2.0.1

### ISSUE THREAD

**Issue by julian-alarcon** [SquadcastHub/terraform-provider-squadcast#88]
I got this error using the latest version 2.0.1 of the Terraform provider:

```sh
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: json: cannot unmarshal string into Go struct field Squad.data.members of type api.Member
│ 
│   with data.squadcast_squad.team,
│   on datasources.tf line 21, in data "squadcast_squad" "team":
│   21: data "squadcast_squad" "team" {
│ 
```

This is my code calling the dataprovider:

```hcl
data "squadcast_squad" "team" {
  name    = "API (${var.domain}-${var.product})"
  team_id = data.squadcast_team.my_team.id
}
```

I'm using Terraform version 1.5.7

**Comment by mohammadmuazam** [comment]
Hi Julian,

Thank you for reporting this. We have reviewed the issue and can confirm that it is valid. We are currently working on a fix and it will be included in the next patch release.

If you have any further questions or additional feedback, please feel free to let us know.

**Comment by mohammadmuazam** [comment]
Hi Julian, 

Please update to v2.1.0 and let us know if you encounter any further issues or have additional feedback.
