### ISSUE TITLE
alert_sources not configureable on squadcast_service

### ISSUE THREAD

**Issue by be-aws-architect** [SquadcastHub/terraform-provider-squadcast#91]
Hi!

I'm trying to create a **squadcast_service** on Terraform and add the Cloudwatch alert source.

There is no definition of what the alert_sources should be named, it refers to the docs of the Alert Integrations but that doesn't give the correct info.

I tried using "cloudwatch" as it is also returned in the "alert_source_endpoints" but that doesn't work.

```

# squadcast_service.rsm will be updated in-place
  ~ resource "squadcast_service" "rsm" {
      ~ alert_sources                 = [
          + "cloudwatch",
        ]
        id                            = "6655bd59aa6e543346d063b2"
        name                          = "RSM"
        # (8 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "prd"?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 

squadcast_service.rsm: Modifying... [id=6655bd59aa6e543346d063b2]
╷
│ Error: cloudwatch is not a valid alert source name. Find all alert sources supported on Squadcast on https://www.squadcast.com/integrations
│ 
│   with squadcast_service.rsm,
│   on main.tf line 32, in resource "squadcast_service" "rsm":
│   32: resource "squadcast_service" "rsm" {
│ 
```

How do I proceed?

**Comment by mohammadmuazam** [comment]
Hi @be-aws-architect,

Thank you for bringing this issue to our attention.

Please use "Amazon CloudWatch" as the Alert Source name. To find the list of all available alert sources, navigate to Services > Select a Service > Add Alert Source and use the name from there.

We apologize for not updating this information on [our integrations page](https://www.squadcast.com/integrations). Our team is currently addressing this.

Thanks again for your feedback. I will be closing this issue now, but please feel free to reopen it if you have any further questions or concerns.

**Comment by be-aws-architect** [comment]
Hi @mohammadmuazam 

Thanks for the quick response.

It however doesn't work.

```│ Error: Amazon Cloudwatch is not a valid alert source name. Find all alert sources supported on Squadcast on https://www.squadcast.com/integrations```


I need to be able to configure when I create a service Cloudwatch as the alert source, and output the SNS Subscription endpoint.
