### ISSUE TITLE
RE: alert_sources not configureable on squadcast_service #91

### ISSUE THREAD

**Issue by be-aws-architect** [SquadcastHub/terraform-provider-squadcast#92]
Hi @mohammadmuazam

Thanks for the quick response.

It however doesn't work.

│ Error: Amazon Cloudwatch is not a valid alert source name. Find all alert sources supported on Squadcast on https://www.squadcast.com/integrations

I need to be able to configure when I create a service Cloudwatch as the alert source, and output the SNS Subscription endpoint.

**Comment by mohammadmuazam** [comment]
Hi @be-aws-architect,

Just a quick note: you should be passing "Amazon CloudWatch" instead of "Amazon Cloudwatch." For more details, please refer to my previous [response](https://github.com/SquadcastHub/terraform-provider-squadcast/issues/91#issuecomment-2136692035).

Thanks!

**Comment by be-aws-architect** [comment]
Thanks! That worked.
